import os

from dotenv import load_dotenv

from langgraph.prebuilt import create_react_agent
from langgraph.store.memory import InMemoryStore

from experimental.agents.models import select_model
from experimental.agents.superstore.tooling import tools
from experimental.agents.superstore.prompt import AGENT_SYSTEM_PROMPT


"""
TABLEAU AGENT

This Agent uses the Langgraph prebuilt `create_react_agent` to handle conversations on Tableau subjects such as:
    - Metrics (canonical source of truth for metrics, includes machine learning insights generated by Tableau Pulse)
    - Workbooks (contains analytics such as dashboards and charts that server as canonical interfaces for data exploration)
    - Data Sources (describes sources of data available for querying and exploration)
    - VizQL Data Service (can query a data source for on-demand data sets including aggregations, filters and calculations)

This represents the most straightforward implementation of Tableau tooling for Langgraph without further customizing the
Agent for specific applications
"""
# environment variables available to current process and sub processes
load_dotenv()

# configure running model for the agent
llm = select_model(
    provider=os.environ["MODEL_PROVIDER"],
    model_name=os.environ["AGENT_MODEL"],
    temperature=0.2
)

# initialize a memory store
memory = InMemoryStore()

# set agent debugging state
if os.getenv('DEBUG') == '1':
    debugging = True
else:
    debugging = False

# define the agent graph
analytics_agent = create_react_agent(
    model=llm,
    tools=tools,
    debug=debugging,
    prompt=AGENT_SYSTEM_PROMPT
)
